import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {extractLeagues,extractTeams,catalogueDigest,key,extractBacktestLeagues,validateSourceCatalogue} from './source-catalog.mjs';
const real=JSON.parse(await readFile(new URL('./tests/fixtures/catalog-real-2026-10-03.json',import.meta.url)));
const approved=JSON.parse(await readFile(new URL('./data/approved-leagues.json',import.meta.url)));
test('49 real leagues match frozen contract',()=>assert.equal(catalogueDigest(extractLeagues({tables:real.leagues})),catalogueDigest(approved.leagues.filter(l=>approved.sourceCatalogues.find(s=>s.id==='statistiche_lega').leagueIds.includes(l.id)))));
test('20 real standings teams extracted',()=>{const t=extractTeams(real.standings);assert.equal(t.length,20);assert.equal(t[0],'EC Juventude');assert.ok(t.includes('Ponte Preta'));});
test('missing league fails closed',()=>assert.throws(()=>extractLeagues({tables:[]})));
test('empty standings never certified',()=>assert.throws(()=>extractTeams({rows:[{cells:[{text:'Squadra'}]}]})));
test('normalization preserves meaningful accents',()=>{assert.equal(key('  Vila   Nova '),'vila nova');assert.notEqual(key('Cuiabá'),key('Cuiaba'));});
test('changed territory changes contract digest',()=>{const l=structuredClone(approved.leagues);l[0].country='CHANGED';assert.notEqual(catalogueDigest(l),catalogueDigest(approved.leagues));});
test('duplicate real team row rejected',()=>{const t=structuredClone(real.standings);t.rows.push(t.rows[1]);assert.throws(()=>extractTeams(t));});

const backtest=JSON.parse(await readFile(new URL('./tests/fixtures/backtest-leagues-real-2026-10-03.json',import.meta.url)));
test('52 real Backtest labels retain territory and sample count',()=>{const r=extractBacktestLeagues(backtest);assert.equal(r.length,52);assert.equal(r.find(l=>l.id==='world uefa nations league').sampleCount,656);assert.equal(r.find(l=>l.id==='world world cup').country,'WORLD');validateSourceCatalogue(approved,'backtest_storico',r);});
test('49 shared identities and three Backtest-only leagues',()=>{const stats=new Set(approved.sourceCatalogues.find(s=>s.id==='statistiche_lega').leagueIds);const bt=extractBacktestLeagues(backtest);assert.equal(bt.filter(l=>stats.has(l.id)).length,49);assert.equal(bt.filter(l=>!stats.has(l.id)).length,3);assert.equal(approved.leagues.length,52);});
test('duplicate Backtest row rejected',()=>{const d=structuredClone(backtest);d.checkboxes.push(d.checkboxes[0]);assert.throws(()=>extractBacktestLeagues(d));});
test('unapproved source membership rejected',()=>assert.throws(()=>validateSourceCatalogue(approved,'backtest_storico',extractBacktestLeagues(backtest).slice(1))));
test('sample updates retain contract, negative counts rejected',()=>{const r=extractBacktestLeagues(backtest);r[0].sampleCount++;validateSourceCatalogue(approved,'backtest_storico',r);r[0].sampleCount=-1;assert.throws(()=>validateSourceCatalogue(approved,'backtest_storico',r));});
