import test from 'node:test';
import assert from 'node:assert/strict';
import {parseBacktestPerformance as parse} from './source-finance.mjs';
const back='La resa della mia strategia\nOPERAZIONI\n2324\n804 vinte · 1520 perse\nPROFITTO TOTALE\n+76,00 €\nROI SUL RISCHIO\n+0,3%\nsu 23240,00 € puntati\nDRAWDOWN MASSIMO\n-1130,00 €';
const lay='La resa della mia strategia\nOPERAZIONI\n2324\n1520 vinte · 804 perse\nPROFITTO TOTALE\n−1640,00 €\nROI SUL RISCHIO\n-3,5%\nsu 46480,00 € puntati\nDRAWDOWN MASSIMO\n-2314,50 €';
const context=side=>({side,odds:3,stake:10,commissionPercent:5});
test('real BACK output reconciles winnings, commission, losses and risk',()=>{const p=parse(back,context('BACK'));assert.equal(p.usable,true);assert.equal(p.expected.profit,76);assert.equal(p.expected.riskTotal,23240);});
test('real LAY output uses liability for total risk',()=>{const p=parse(lay,context('LAY'));assert.equal(p.usable,true);assert.equal(p.expected.profit,-1640);assert.equal(p.expected.riskTotal,46480);});
test('changed profit cannot enter financial analysis',()=>assert.equal(parse(back.replace('+76,00','+800,00'),context('BACK')).usable,false));
test('missing context or inconsistent sample fails closed',()=>{assert.equal(parse(back).usable,false);assert.equal(parse(back.replace('804 vinte','805 vinte'),context('BACK')).usable,false);assert.equal(parse(back,{...context('BACK'),odds:1}).usable,false);});
test('extra source sections preserve known output',()=>assert.equal(parse(back+'\nNUOVO CONTROLLO\nNuova funzione',context('BACK')).usable,true));
test('malformed localized money cannot masquerade as a correct result',()=>assert.equal(parse(back.replace('+76,00','+7.6,00'),context('BACK')).usable,false));
